apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels: 
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: docker.io/qamattjohunt/playground:latest
        ports:
        - containerPort: 8080
