apiVersion: v1
kind: Pod
metadata:
  name: mongo-seed
  labels:
    app: mongo-seed
spec:
  containers:
    - name: mongo-seed
      image: fvilers/mongo-seed:1.0.0:latest
      env:
      - name: MONGO_HOST
        value: "mongo"
      - name: MONGO_PORT
        value: "27017"
      command: ["mongoimport", "--host mongo", "--port 27017", "--db test", "--mode upsert", "--type json", "--file /data/account.json", "--jsonArray"]
      volumeMounts:
        # directory location on container
        - mountPath: "/data"
          name: data
  restartPolicy: OnFailure
  volumes:
    - name: data
      hostPath:
        # directory location on host
        path: ./data
